DROP TABLE PRODUCT;
DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
    CUST_ID NUMBER PRIMARY KEY,
    CREDITCARD_AMOUNT NUMBER
);

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    PRICE NUMBER NOT NULL,
    AMOUNT NUMBER
);

DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

INSERT INTO PRODUCT
VALUES (SEQ_USERNO.NEXTVAL, '코카콜라', 2200, 14);

INSERT INTO PRODUCT
VALUES (SEQ_USERNO.NEXTVAL, '펩시', 2000, 20);

INSERT INTO PRODUCT
VALUES (SEQ_USERNO.NEXTVAL, '칠성사이다', 2100, 10);

INSERT INTO PRODUCT
VALUES (SEQ_USERNO.NEXTVAL, '포카리스웨트', 1500, 0);

INSERT INTO PRODUCT
VALUES (SEQ_USERNO.NEXTVAL, '제주삼다수', 900, 11);

COMMIT;

SELECT * FROM PRODUCT;
