DROP TABLE PRODUCT;
--DROP TABLE CREDITCARD;

--CREATE TABLE CREDITCARD(
--    CARD_ID NUMBER PRIMARY KEY,
--    CARDNUMBER NOT NULL,
--    BANK_NAME VARCHAR2(20) NOT NULL
--);

CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    --CATEGORY VARCHAR2(20) CHECK(CATEGORY IN('탄산음료', '이온음료', '생수', '에너지드링크', '유제품', '주류')),
    PRICE NUMBER NOT NULL,
    AMOUNT NUMBER DEFAULT 0 NOT NULL,
    
);

COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품ID';
COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품명';
--COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '종류';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.AMOUNT IS '재고';

DROP SEQUENCE SEQ_PRODUCTNO;
CREATE SEQUENCE SEQ_PRODUCTNO
NOCACHE;

INSERT INTO PRODUCT VALUES (SEQ_PRODUCTNO.NEXTVAL, '코카콜라', 2200, 14);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCTNO.NEXTVAL, '펩시', 2000, 20);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCTNO.NEXTVAL, '칠성사이다', 2100, 10);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCTNO.NEXTVAL, '포카리스웨트', 1500, DEFAULT);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCTNO.NEXTVAL, '제주삼다수', 900, 11);

COMMIT;

CREATE TABLE PAYMENT(
    
)



SELECT * FROM PRODUCT;
