DROP TABLE PAYMENT;
DROP TABLE CREDITCARD;
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT( --상품 테이블
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(50) NOT NULL,
    CATEGORY VARCHAR2(20) DEFAULT '음료' CHECK(CATEGORY IN('음료', '탄산음료', '이온음료', '생수', '에너지드링크', '커피', '유제품')),
    PRICE NUMBER NOT NULL,
    AMOUNT NUMBER DEFAULT 0 NOT NULL
);
COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품ID';
COMMENT ON COLUMN PRODUCT.PRODUCT_NAME IS '상품명';
COMMENT ON COLUMN PRODUCT.CATEGORY IS '종류';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.AMOUNT IS '재고';

DROP SEQUENCE SEQ_PRODUCT_NO;
CREATE SEQUENCE SEQ_PRODUCT_NO
NOCACHE;

INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, '코카콜라', '탄산음료', 2200, 14);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, '펩시', '탄산음료', 2000, 20);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, '칸타타', '커피', 2100, 10);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, '포카리스웨트', '이온음료', 1500, DEFAULT);
INSERT INTO PRODUCT VALUES (SEQ_PRODUCT_NO.NEXTVAL, '제주삼다수', '생수', 900, 11);

COMMIT;

CREATE TABLE CREDITCARD( --카드 정보 테이블
    CARD_ID NUMBER PRIMARY KEY,
    CARD_NUMBER CHAR(19) NOT NULL,
    BANK_NAME VARCHAR2(20) NOT NULL,
    MONEY NUMBER DEFAULT 0 NOT NULL,
    CARD_NICKNAME VARCHAR2(60)
);
COMMENT ON COLUMN CREDITCARD.CARD_ID IS '카드ID';
COMMENT ON COLUMN CREDITCARD.CARD_NUMBER IS '카드번호(''-''포함)';
COMMENT ON COLUMN CREDITCARD.BANK_NAME IS '카드사은행';
COMMENT ON COLUMN CREDITCARD.BANK_NAME IS '보유금액';
COMMENT ON COLUMN CREDITCARD.BANK_NAME IS '카드별칭';

DROP SEQUENCE SEQ_CARD_ID;
CREATE SEQUENCE SEQ_CARD_ID START WITH 100
NOCACHE;

INSERT INTO CREDITCARD VALUES (SEQ_CARD_ID.NEXTVAL, 1231-1234-1234-1111, '국민', 100000, '메인카드');

COMMIT;

DROP SEQUENCE SEQ_PAYMENT_CODE;
CREATE SEQUENCE SEQ_PAYMENT_CODE START WITH 200
NOCACHE;

CREATE TABLE PAYMENT( --결제 정보 테이블
    PAY_CODE NUMBER PRIMARY KEY,
    PYA_COST NUMBER DEFAULT 0,
    CARD_ID NUMBER REFERENCES CREDITCARD, --CREDITCARD 테이블의 기본키 참조(외래키)
    PAY_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN PAYMENT.PAY_CODE IS '결제코드';
COMMENT ON COLUMN PAYMENT.PYA_COST IS '결제금액';
COMMENT ON COLUMN PAYMENT.CARD_ID IS '결제카드ID';
COMMENT ON COLUMN PAYMENT.PAY_DATE IS '결제날짜';

COMMIT;

SELECT * FROM PRODUCT;
